const path = require('path');

module.exports = {
  dependencies: {
    // react-native-config 1.6.1 has no `react-native` field in its package.json,
    // so the autolinking system returns android: null. Provide the config explicitly.
    'react-native-config': {
      platforms: {
        android: {
          sourceDir: path.resolve(
            __dirname,
            'node_modules/react-native-config/android',
          ),
          packageImportPath: 'import com.lugg.RNCConfig.RNCConfigPackage;',
          packageInstance: 'new RNCConfigPackage()',
          // Required so RNGP compiles the codegen JNI bridge for the TurboModule.
          // Path is generated by the first Gradle build (after codegen runs).
          libraryName: 'RNCConfigSpec',
          cmakeListsPath: path.resolve(
            __dirname,
            'node_modules/react-native-config/android/build/generated/source/codegen/jni/CMakeLists.txt',
          ),
          componentDescriptors: [],
        },
      },
    },
  },
};
